#!/bin/bash

set -ex

echo "DEFAULT_SERVER_ADDRESS=$DEFAULT_SERVER_ADDRESS"

cd $(dirname ${BASH_SOURCE[0]})

spectrumFeed="crts_spectrumFeed"


exec $spectrumFeed --address $DEFAULT_SERVER_ADDRESS $*
