#!/bin/bash

set -ex

echo "LAUNCH_ID=$LAUNCH_ID"
echo "SERVER_ADDRESS=$SERVER_ADDRESS"
echo "SPECTRUM_PORT=$SPECTRUM_PORT"


cd $(dirname ${BASH_SOURCE[0]})

# We use the PATH to find the program to run:
spectrumFeed="crts_spectrumFeed"


exec $spectrumFeed --address $SERVER_ADDRESS --port $SPECTRUM_PORT $*
